name: MobArena
version: '${project.version}'
main: me.blacbrd123.untitled.MobArena
api-version: '1.20'
commands:
  startWave:
    description: Lets you pick a kit and start a mob wave
    usage: /<command>

